### ISSUE TITLE
Bug: West Europe location for deploying bicep Azure resource in the RG is hard coded

### ISSUE THREAD

**Issue by kal1mera** [cloudyspells/PsrAzDo-workbooks#4]
# **🐞 Bug Report**

## **Describe the bug**
The Azure location 'West Europe' is hard-coded in the resource deployment of the bicep template. For example I have created my RG in 'eastus' and I need all my resources to be created in 'eastus'. However, the resources are created by default in 'west europe'. May have the $location as input variable in the 'az deployment group create' script for the main.bicep?

*

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* OS: 
* PowerShell version:
* PSRule version:
* PSRule.Rules.AzureDevOps version:

---

### **Additional context**

*

**Comment by kal1mera** [comment]
I forgot to add a screenshot for this Issue. So here you go:

Resource Group Location
![image](https://github.com/cloudyspells/PsrAzDo-workbooks/assets/57422595/59d5fe16-d333-473d-8fdf-eed0a0688ac7)

Resources created in Resource Group
![image](https://github.com/cloudyspells/PsrAzDo-workbooks/assets/57422595/304c7f04-726f-4165-a01a-b2f0bec56b38)

**Comment by webtonize** [comment]
Changed the default behaviour of the deployment to follow the location of the resourcegroup for all resources. A Bicep parameter is available for an override.
