### ISSUE TITLE
Bug: Bicep Deployment Fails because it finds a duplicate vault in western europe with name 'kv-psrule-azdo-prd-weu'

### ISSUE THREAD

**Issue by kal1mera** [cloudyspells/PsrAzDo-workbooks#5]
# **🐞 Bug Report**

## **Describe the bug**
Probably this happens because the Vault name defined in the Bicep template is static and the location is hard coded to western europe, where this vault already exists. Maybe add a random suffix in the vault's name?

![image](https://github.com/cloudyspells/PsrAzDo-workbooks/assets/57422595/7ae5cab5-60e8-4ad2-9c0a-59f511bfa31f)

*

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* OS: 
* PowerShell version:
* PSRule version:
* PSRule.Rules.AzureDevOps version:

---

### **Additional context**

*

**Comment by webtonize** [comment]
Fixed this by using a `uniqueString` as part of the resource name for Key Vault and Log Analytics workspace. Base for the uniquestring is the subscription and resourcegroup id.
